name: cobblestone
description: A dart game framework.
version: 0.0.1
#author: Ethan Tucker <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'
  simple_audio:
    git: https://github.com/johnmccutchan/simpleaudio.git
  vector_math: any
  xml: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'

transformers:
- dart_to_js_script_rewriter
