name: cobblestone
description: >-
  A mid-level 2D game framework, providing WebGL rendering, audio playing, tilemaps, particle effects, tweens, and more.
version: 0.3.4
author: Ethan Tucker <ectucker1@gmail.com>
homepage: https://gitlab.com/ectucker/cobblestone
issue_tracker: https://gitlab.com/ectucker/cobblestone/issues

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  vector_math: ^2.0.8
  path: ^1.6.2
  xml: ^4.1.0
  petitparser: ^3.0.0

dev_dependencies:
  build_runner: ^1.8.1
  build_web_compilers: ^2.6.1
  pedantic: ^1.9.0