name: cobblestone
description: A dart game framework.
version: 0.2.6
#author: Ethan Tucker <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  vector_math: any
  path: any
  xml: any
  petitparser: ^2.1.1

dev_dependencies:
  build_runner: ^1.3.0
  build_web_compilers: ^2.0.0

web:
  compiler:
    debug: dart2js
    release: dart2js