name: cobblestone
description: A dart game framework.
version: 0.3.0
#author: Ethan Tucker <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  vector_math: any
  path: any
  xml: any
  petitparser: ^2.1.1

dev_dependencies:
  build_runner: ^1.6.2
  build_web_compilers: ^2.0.0
  pedantic: ^1.7.0

web:
  compiler:
    debug: dartdevc
    release: dart2js