name: cobblestone
description: >-
  A mid-level 2D game framework, providing WebGL rendering, audio playing, tilemaps, particle effects, tweens, and more.
version: 0.3.2
author: Ethan Tucker
homepage: https://gitlab.com/ectucker/cobblestone
issue_tracker: https://gitlab.com/ectucker/cobblestone/issues

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  vector_math: ^2.0.8
  path: ^1.6.2
  xml: ^3.5.0
  petitparser: ^2.4.0

dev_dependencies:
  build_runner: ^1.6.2
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0