name: cobblestone
description: A dart game framework.
version: 0.1.5
#author: Ethan Tucker <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  vector_math: any
  path: any
  xml: any

dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^0.4.4

web:
  compiler:
    debug: dart2js
    release: dart2js